# August 21, 2015
# https://github.com/bevry/base

# Use the latest travis infrastructure
sudo: false

# We use node
language: node_js
node_js:
  - iojs
cache:
  directories:
    - node_modules

# Prepare and run our tests
script: "npm test"

# Custom notifications
notifications:
  # Notify email travisci@bevry.me
  email:
    recipients:
      - travisci@bevry.me

  # Notify slack bevry#updates on https://bevry.slack.com
  # Bevry's token available from https://bevry.slack.com/services/4200459714
  # travis encrypt "$SLACK_SUBDOMAIN:$SLACK_TRAVIS_TOKEN#updates" --add notifications.slack
  slack:
    secure: TXhffbJwQRIT+9sxFvi/aW8mvE0+IpDyjW5V0nfhjEuyhqsocBQi15rxxfubha9rSs/f1aCoWnH6H5YcrffT8dtVJTe6inKNO0B/JNJa4bIb20+QfoFo2AzMdtxEZPKhy+dEtPW7n9AJrItLVnz5SpqkBkjV0P+rJMTih7ZYtF4=

# Custom deployment
# travis encrypt DEPLOY_TOKEN=$GITHUB_TRAVIS_TOKEN --add env.global
env:
  global:
    - DEPLOY_EMAIL='travisci@bevry.me'
    - DEPLOY_NAME='Bevry Travis CI Deployer'
    - DEPLOY_USER='balupton'
    - DEPLOY_REPO='docpad/website'
    - secure: WzTH+oFp94kD1tq5+yoX/mt2p/omlikss8ZZyV9ugUcIJHdEE9wxcilDjqeNzUvH43vtZzaKTNA7PvbKfLAzg25VRc2sRWFEhtL61El9FllDnAYIEW7nmwc8cKUj5LcV1DdA0nI0Sql3j8K4OHVB8gbcEgvhbRTk4r34wiV4gJU=
after_success: >
  if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) &&
      [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "Deploying"
    git config --global user.email $DEPLOY_EMAIL
    git config --global user.name $DEPLOY_NAME
    git remote rm origin
    git remote add origin "https://$DEPLOY_USER:$DEPLOY_TOKEN@github.com/$DEPLOY_REPO.git"
    npm run-script deploy
    echo "Deployed"
  else
    echo "Skipped deploy"
  fi
