# August 21, 2015
# https://github.com/bevry/base

# Use the latest travis infrastructure
sudo: false

# We use node
language: node_js
node_js:
  - iojs
cache:
  directories:
    - node_modules

# Ensure npm is the latest version (ignore node versions that can't run it)
install: "npm install -g npm && npm install"
script: "npm test"

# Custom configuration
notifications:
  # Nofity email travisci@bevry.me
  email:
    recipients:
      - travisci@bevry.me

  # Notify slack bevry#updates
  slack:
    secure: TXhffbJwQRIT+9sxFvi/aW8mvE0+IpDyjW5V0nfhjEuyhqsocBQi15rxxfubha9rSs/f1aCoWnH6H5YcrffT8dtVJTe6inKNO0B/JNJa4bIb20+QfoFo2AzMdtxEZPKhy+dEtPW7n9AJrItLVnz5SpqkBkjV0P+rJMTih7ZYtF4=

# Deployment
env:
  global:
    secure: "BAWV2Gc+9wgcqygqaSMN1KXfqxi/DRupGd/9flHuIWgikCWQAdMAHmAWZKVh6/bYwGeW7ZVA+hZeBoQBMd6RSPsAi3LTOE/KzUU8edYoibtlF5EMHgOc1rqe5sGzlMdIc2htx5dHOgXP5tr+PcIsCoTeOiKgbCGHxuKcqaQgFMQ="
after_success:
  - git remote rm origin
  - git remote add origin "https://$GITHUB_AUTH@github.com/docpad/website.git"
  - npm run-script deploy
