sudo: false
language: node_js
node_js:
- '8'
matrix:
  fast_finish: true
  allow_failures: []
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/15760d3/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/15760d3/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/15760d3/scripts/deploy-now.bash)"
notifications:
  email:
    recipients:
      secure: fqkq8TENtt2Qb/iAFepEToCu8Xf81j0Lpa1n1V0i4Qb6uMPJF9Unt7rZaCrMUvv/WmvfnGMQOPz0F7Bgk/4RymvXtjOmnISe/4NN5r2qQu4WCdzbxJ3a2zQCor198HHA53emw9T5jQ4z7IuULCy8FH99QV2B9GdW2iV7mTrKrIw=
